//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SehirDetay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.Icerik = new HashSet<Icerik>();
            this.KullaniciRol = new HashSet<KullaniciRol>();
            this.Yorum = new HashSet<Yorum>();
        }
    
        public int Id { get; set; }
        public string Eposta { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<bool> Cinsiyet { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public Nullable<long> CepTelefonu { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> SehirId { get; set; }
        public Nullable<int> IlceId { get; set; }
        public bool Aktif { get; set; }
        public string AktivasyonKodu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Icerik> Icerik { get; set; }
        public virtual Ilce Ilce { get; set; }
        public virtual Sehir Sehir { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRol> KullaniciRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
    }
}
