//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SehirDetay.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SehirDetayEntities : DbContext
    {
        public SehirDetayEntities()
            : base("name=SehirDetayEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ayar> Ayar { get; set; }
        public virtual DbSet<Icerik> Icerik { get; set; }
        public virtual DbSet<Ilce> Ilce { get; set; }
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<Kullanici> Kullanici { get; set; }
        public virtual DbSet<KullaniciRol> KullaniciRol { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Sehir> Sehir { get; set; }
        public virtual DbSet<Ulasim> Ulasim { get; set; }
        public virtual DbSet<UlasimTur> UlasimTur { get; set; }
        public virtual DbSet<Yorum> Yorum { get; set; }
        public virtual DbSet<IcerikMedya> IcerikMedya { get; set; }
        public virtual DbSet<Medya> Medya { get; set; }
    }
}
