//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SehirDetay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public long Id { get; set; }
        public long IcerikId { get; set; }
        public int KullaniciId { get; set; }
        public string YorumMetni { get; set; }
        public int Puan { get; set; }
        public System.Data.Entity.Spatial.DbGeography Konum { get; set; }
        public System.DateTime OlusturulmaTarihi { get; set; }
        public System.DateTime GuncellenmeTarihi { get; set; }
    
        public virtual Icerik Icerik { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
